FROM quay.io/fedora/fedora@sha256:91de50d5e86946a31db8b210009b11fb35d34125689568c5c24f6bdfbf64228a AS keylime_base
LABEL version="_version_" description="Keylime Base - Only used as an base image for derived packages"
MAINTAINER Keylime Team <main@keylime.groups.io>

RUN dnf -y install \
    awk \
    dnf-plugins-core \
    efivar-devel \
    efivar-libs \
    git \
    nc \
    python3-PyMySQL \
    python3-jinja2 \
    python3-psycopg2 \
    tpm2-tools
